# -*- coding: utf-8 -*-
"""Bahae Eddine - Groupe Soir.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cGXsBEpPsZWyqEQCyFJjMfdL4vsJQnEd

Release Date,Movie Title,Production Budget,Domestic Gross,Worldwide Gross

**1.	Qui sauvegarde dans un dictionnaire D toutes ses données où la clé est le payé « Movie Title » et la valeur et une liste qui contient toutes les informations sur les films.**
"""

import pandas as pd

# Create a dataframe from csv
df = pd.read_csv('/content/top_4000_movies_data2.csv', delimiter=',' , encoding= 'unicode_escape')

# User list comprehension to create a list of lists from Dataframe rows
list_of_rows = [list(row) for row in df.values]


print(list_of_rows)

"""**2.	Créez un tuple des films où la « Production Budget » et supérieure à la « worldwide Gross ».**"""

subset = df[['Production Budget', 'Worldwide Gross']]
tuples = [tuple(x) for x in subset.to_numpy()]

print(tuples)


df_tuples = pd.DataFrame (tuples)

"""**3.	Créez une liste de sous liste, chaque sous liste contient le nom principale d’un film et les différents noms de ses éditions**"""

new_list = df['Movie Title'].str.split(':')
df2 = pd.DataFrame(new_list)
new_list2 = df2.values.tolist()
print(new_list2)

"""**4.	Cherchez le budget de production total des films entre 2005 et 2020 et affichez le film dans cette période qui a fait la plus grande recette.**"""

print("Le budget de production total des films entre 2005 et 2020 est :")
df.loc[(df['Release Date'] > "01/01/2005") & (df['Release Date'] <= "30/12/2020"), 'Production Budget'].sum()

"""Affichez le film dans cette période qui a fait la plus grande recette"""

df['Total_Gross'] =  df['Domestic Gross'] + df['Worldwide Gross']  
print(df['Total_Gross'])

#Affichez le film dans cette période qui a fait la plus grande recette
df['Total_Gross'].max()

"""**5.	Sauvegardez les résultats de la question 2 dans un autre fichier CSV "sauvegarde.csv".**"""

df_tuples.to_csv("sauvegarde.csv", index=False)
